# Generated by Django 6.0 on 2026-08-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_experience_project_service_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
        migrations.AddField(
            model_name='education',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HeroTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='portfolio.hero')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
